### ISSUE TITLE
retro.zip corrupt

### ISSUE THREAD

**Issue by yaroslavvb** [TobiasNorlund/retro#2]
The file appears corrupt

```
(base) ÷23-09-25 18:47:39|ttys009|Yaroslavs-MacBook-Pro-2|~/Downloads/temp\÷ ls -l retro.zip
-rw-r--r--@ 1 yaroslavvb  staff  6899134168 Sep 20 10:31 retro.zip

(base) ÷23-09-25 18:47:27|ttys009|Yaroslavs-MacBook-Pro-2|~/Downloads/temp\÷ zip -T retro.zip
	zip warning: missing end signature--probably not a zip file (did you
	zip warning: remember to use binary mode when you transferred it?)
	zip warning: (if you are trying to read a damaged archive try -F)

zip error: Zip file structure invalid (retro.zip)
```

I tried this using zip on MacOS (`brew install zip`) and also `zip` on a Debian 11  (`sudo apt install zip`), same error message

Using MacOS built-in "Extractor" it appears to extract some partial files with numeric names like "1" etc. There's no `model.ckpt` to be found
<img width="202" alt="Screenshot 2023-09-25 at 6 49 49 PM" src="https://github.com/TobiasNorlund/retro/assets/23068/5c0cadae-276e-4b48-be5e-0551ec6a7886">

**Comment by TobiasNorlund** [comment]
Thanks for letting me know. I have updated the file in the link :)

**Comment by yaroslavvb** [comment]
The new checkpoint appears to load successfully, thanks for making this reproducible :)
