### ISSUE TITLE
Difference to lucidrains/RETRO-pytorch

### ISSUE THREAD

**Issue by Muennighoff** [TobiasNorlund/retro#4]
Hey what's the difference btw your code & `lucidrains/RETRO-pytorch`? Are there any mistakes in the lucidrains impl.?

**Comment by TobiasNorlund** [comment]
I haven't checked very closely to be honest. I wanted to be certain the implementation works the way I understand RETRO so I decided to implement myself. One difference is the positional encoding, where I use positional biases similar to T5 where `lucidrains/RETRO-pytorch` uses rotary embeddings if I'm not mistaken.

**Comment by sdake** [comment]
@Muennighoff from a scale perspective, Tobias has done a lovely job here.

From an integrated training perspective, lucidrains implementation was easier (for me)..

Do you believe there are errors in lucidrains implementation?

One significant difference is the embedding model (in this repo, sentence transformers).

Happy to hear your thoughts!

Also, our work on retro, thus far, based upon lucid's work, is here:

https://github.com/artificialwisdomai/origin/blob/main/workloads/retroformer
