### ISSUE TITLE
Model.zip link is not available

### ISSUE THREAD

**Issue by tiannuo-yang** [TobiasNorlund/retro#7]
Hi there! Your work is very impressive! I want to reproduce Retro with model inference and retrieval, rather than training it from the very beginning. But the checkpoint file (model.zip) link in your github is nor available any more. Could you please provide the feasible access to that file? Thanks a lot!!!

**Comment by TobiasNorlund** [comment]
Hi @tiannuo-yang and thanks for the kind words! I updated the link, so hopefully it should work now!

Good luck with your experiments!
